name: CICD

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        run: sudo docker login -u arjunsingh0528159@gmail.com -p Samarpal08@
      - name: Build Docker Image
        run: sudo docker build -t aarjun8060/relaxo_frontend .
      - name: Publish image to docker hub
        run: sudo docker push aarjun8060/relaxo_frontend

  deploy: 
    needs: build
    runs-on: aws-ec2    
    steps:
      - name: Pull image from docker hub
        run: sudo docker pull reactjs-app:latest 
      - name: Delete Old Container
        run: sudo docker rm -f reactContainer
      - name: Run docker container
        run: sudo docker run -d -p 3000:80 --name reactContainer aarjun8060/relaxo_frontend   
